#!/usr/bin/bash

app_name="Localization"
echo "building for app = ${app_name}"

# cleanup
rm -R dist
rm -R build
rm -R "${app_name}.spec"
find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf

# compile
python setup.py build_ext --inplace

# bundle
pyinstaller \
    --onefile \
    --name "${app_name}" \
	--add-binary="image_pad.cpython-310-x86_64-linux-gnu.so:app/some_package/" \
    Localization.py
